services:
  flowise:
    image: flowiseai/flowise
    container_name: flowise
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/ubuntu/.flowise:/root/.flowise
      - ./.flowise/api.json:/root/.flowise/api.json:ro
      - ./flowise-entrypoint.sh:/usr/local/bin/flowise-entrypoint.sh:ro
      - flowise_modules:/usr/local/lib/node_modules/flowise
    entrypoint: ["sh", "/usr/local/bin/flowise-entrypoint.sh"]
    ports:
      - "3000:3000"
  frontend:
    image: ${FRONTEND_IMAGE:-flowise-react-app:latest}
    build:
      context: .
      args:
        REACT_APP_CHATFLOW_ID: "${CHATFLOW_ID:-}"
        REACT_APP_API_HOST:     "${REACT_APP_API_HOST:-}"
    env_file:
      - .env
    ports:
      - "3001:3000"
volumes:
  flowise_modules:
